---
name: pipeline
pack: umccr
description: UMCCR trigger used to notify of pipeline events.
# payload:
#  - task           : [REQUIRED] The pipeline task/step this events relate to
#  - status         : [REQUIRED] The return status of the task, either 'success' or 'failure'
#  - error_message  : [OPTIONAL] A descrption of the error in case of task failure
#  - runfolder      : [REQUIRED] The full path of the runfolder
#  - workdir        : [OPTIONAL] The name of the directory that the action is working on
