---
name: on_bcl2fastq_success
pack: umccr
description: Rule to act on umccr.bcl2fastq trigger instances
enabled: false

trigger:
  type: umccr.pipeline

criteria:
  trigger.task:
    type: "equals"
    pattern: "bcl2fastq_start"
  trigger.status:
    type: "equals"
    pattern: "success"

action:
  ref: umccr.runfolder_checksums
  parameters:
    runfolder_name: "{{ trigger.runfolder_name }}"
    port: 2222
