---
name: on_bcl2fastq_failure
pack: umccr
description: Rule to act on umccr.bcl2fastq trigger instances
enabled: false

trigger:
  type: umccr.bcl2fastq

criteria:
  trigger.status:
    pattern: "error"
    type: equals

action:
  ref: chatops.post_message
  parameters:
    message: "bcl2fastq conversion failed for {{ trigger.runfolder_name }}! {{ trigger.error_message }}"
    channel: "{{ st2kv.system.slack.channel }}"
