---
name: on_bcl2fastq_success
pack: umccr
description: Rule to act on umccr.bcl2fastq trigger instances
enabled: false

trigger:
  type: umccr.bcl2fastq

criteria:
  trigger.status:
    pattern: "done"
    type: equals

action:
  ref: umccr.incoming_wf
  parameters:
    runfolder_name: "{{ trigger.runfolder_name }}"
    workflow: "umccr.incoming_wf.checksum"
    out_dir: "{{ trigger.out_dir }}"
