---
name: on_checksum_failure
pack: umccr
description: Rule to act on umccr.checksum trigger instances
enabled: false

trigger:
  type: umccr.pipeline

criteria:
  trigger.status:
    type: "nequals"
    pattern: "0"

action:
  ref: chatops.post_message
  parameters:
    message: "Pipeline task {{ trigger.task }} for {{ trigger.runfolder_name }} failed!"
    channel: "{{ st2kv.system.slack.channel }}"
