---
name: on_checksum_failure
pack: umccr
description: Rule to act on umccr.checksum trigger instances
enabled: false

trigger:
  type: umccr.checksum

criteria:
  trigger.status:
    pattern: "error"
    type: equals

action:
  ref: chatops.post_message
  parameters:
    message: "Checksum creation for {{ trigger.usecase }} of {{ trigger.runfolder_name }} failed!"
    channel: "{{ st2kv.system.slack.channel }}"
