---
name: on_checksum_bcl2fastq_success
pack: umccr
description: Rule to act on umccr.pipeline trigger instances related to bcl2fastq checksumming events.
enabled: false

trigger:
  type: umccr.pipeline

criteria:
  trigger.task:
    type: "equals"
    pattern: "checksum.bcl2fastq"
  trigger.status:
    type: "equals"
    pattern: "success"

action:
  ref: umccr.rsync2hpc
  parameters:
    usecase: "runfolder"
    runfolder_name: "{{ trigger.runfolder_name }}"
    source_path: "{{ st2kv.system.runfolder.base.path }}/{{ trigger.runfolder_name }}"
    dest_path: "{{ st2kv.system.pipeline.data.base.path }}/Fastq/"
    excludes: "--exclude Data --exclude Thumbnail_Images"
