---
name: on_checksum_runfolder_success
pack: umccr
description: Rule to act on umccr.pipeline trigger instances related to runfolder checksumming events.
enabled: false

trigger:
  type: umccr.pipeline

criteria:
  trigger.task:
    type: "equals"
    pattern: "checksum.runfolder"
  trigger.status:
    type: "equals"
    pattern: "0"

action:
  ref: umccr.bcl2fastq_checksums
  parameters:
    runfolder_name: "{{ trigger.runfolder_name }}"
    port: 2222
