---
name: on_checksum_runfolder_success
pack: umccr
description: Rule to act on umccr.pipeline trigger instances related to runfolder checksumming events.
enabled: false

trigger:
  type: umccr.pipeline

criteria:
  trigger.task:
    type: "equals"
    pattern: "rsync2hpc.runfolder"
  trigger.status:
    type: "equals"
    pattern: "success"

action:
  ref: umccr.rsync2hpc
  parameters:
    usecase: "bcl2fastq"
    runfolder_name: "{{ trigger.runfolder_name }}"
    source_path: "{{ st2kv.system.bcl2fastq.output.base.path }}/{{ trigger.runfolder_name }}"
    dest_path: "{{ st2kv.system.pipeline.data.base.path }}/Fastq/{{ trigger.runfolder_name }}/"
