---
name: on_samplesheet_check_success
pack: umccr
description: Rule to act on umccr.pipeline trigger instances related to runfolder samplesheet check events.
enabled: false

trigger:
  type: umccr.pipeline

criteria:
  trigger.task:
    type: "equals"
    pattern: "samplesheet_check"
  trigger.status:
    type: "equals"
    pattern: "0"

action:
  ref: umccr.bcl2fastq_start
  parameters:
    runfolder_name: "{{ trigger.runfolder_name }}"
    port: 2222
