---
name: umccr-runfolder-notify
pack: umccr
description: "UMCCR rule acting on new runfolder triggers, notifying of new runfolders."
enabled: false

trigger:
  type: arteria.incoming_ready

criteria:  {}

action:
  ref: umccr.samplesheet_check
  parameters:
    runfolder: "{{trigger.runfolder}}"
    runfolder_name: "{{trigger.runfolder_name}}"
