---
name: umccr-runfolder-kickoff
pack: umccr
description: "UMCCR rule acting on new runfolder triggers, kicking off the first workflow."
enabled: false

trigger:
  type: arteria.incoming_ready

criteria:  {}

action:
  ref: umccr.playground
  parameters:
    runfolder: '{{trigger.runfolder}}'
    runfolder_name: '{{trigger.runfolder_name}}'
    runfolder_host: 172.19.0.1
    bcl2fastq_host: 172.19.0.1
    rsync_dest_host: spartan.hpc.unimelb.edu.au
    rsync_dest_path: '{{trigger.destination}}'
    rsync_user: '{{trigger.remote_user}}'
