---
name: umccr-runfolder-kickoff
pack: umccr
description: "UMCCR rule acting on new runfolder triggers, kicking off the first workflow."
enabled: false

trigger:
  ref: arteria.incoming_ready
  type: arteria.incoming_ready
  parameters:
criteria:
action:
  ref: umccr.playground
  parameters:
    rsync_dest_host: spartan.hpc.unimelb.edu.au
    rsync_user: '{{trigger.remote_user}}'
    rsync_dest_path: '{{trigger.destination}}'
    runfolder: '{{trigger.runfolder}}'
    runfolder_host: 172.19.0.1
