---
name: umccr-runfolder-notify
pack: umccr
description: "UMCCR rule acting on new runfolder triggers, notifying of new runfolders."
enabled: false

trigger:
  type: arteria.incoming_ready

criteria:  {}

action:
  ref: umccr.incoming_wf
  parameters:
    runfolder_name: "{{ trigger.runfolder_name }}"
